# Generated by Django 3.2 on 2021-06-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1_simbathon5', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.IntegerField()),
                ('writer', models.CharField(max_length=200)),
                ('room', models.CharField(max_length=100)),
                ('res_time', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Reserv',
        ),
    ]
