# Generated by Django 3.2 on 2021-06-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1_simbathon5', '0002_auto_20210624_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='res_time',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='room',
            new_name='pub_date',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='writer',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='stu_id',
        ),
        migrations.AlterField(
            model_name='faq',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
